# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target ‘iOrder’ do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    pod 'AFNetworking'
    pod 'FMDB'
    pod 'RDVTabBarController'
    pod 'SDCycleScrollView'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'FSCalendar'
    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'AprilSDK'
    pod 'Reveal-SDK', '~> 4'
    pod 'IQKeyboardManager'
    # Pods for iOrder
    
    target 'iOrderTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'iOrderUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end


