platform :ios, '8.0'

target ‘iOrder’ do
pod 'AFNetworking', '~> 3.0'
pod 'FMDB'
pod 'Reveal-iOS-SDK'
pod 'RDVTabBarController'
pod 'SDCycleScrollView','~> 1.64'
pod 'MJExtension'
pod 'MJRefresh'
pod 'FSCalendar'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry'
pod 'AprilSDK'
end


